#! /bin/sh

case "$1" in
	start|"")
		swupdate  -k /etc/swupdate/swupdate-public.pem -w  ' --document-root /var/www/swupdate' &
		;;
	stop)
		killall swupdate
		killall udhcpc
		;;
	*)
		echo "Usage: $0 {start|stop}" >&2
		exit 1
		;;
esac
